DROP SCHEMA IF EXISTS parameterization CASCADE;
DROP SCHEMA IF EXISTS distribution CASCADE;
DROP SCHEMA IF EXISTS service_provision CASCADE;
DROP SCHEMA IF EXISTS bill CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS notification CASCADE;
DROP SCHEMA IF EXISTS security CASCADE;
DROP SCHEMA IF EXISTS maintenance CASCADE;
